server:
  port : 8080
#  servlet :
#    context-path: /identity
# tạo biến môi trường và gán
spring :
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa :
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "WHoXAMeaioBEovwVedUCB6lTNgEHL1zUGN/j9cpPmkqkceAvSFHmxTfm4rAvH069"
  valid-duration: 3600 #giây
  refreshable-duration: 36000 #giây
